name: Sync flomo from Notion database to Readwise

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sync flomo from Notion database to Readwise
      run: python flomo2readwise.py
      env:
        NOTION_INTEGRATION_TOKEN: ${{ secrets.NOTION_INTEGRATION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        READWISE_ACCESS_TOKEN: ${{ secrets.READWISE_ACCESS_TOKEN }}

    # - name: Commit changes
    #   run: |
    #     git config --local user.name "github-actions"
    #     git config --local user.email "actions@github.com"
    #     git add last_sync_time.txt flomo2readwise.log
    #     git commit -m "Update sync time and log [skip ci]"
    #     git remote set-url origin https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/Bachery/flomo2Readwise.git
    #     git push
    #   env:
    #     GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update sync time and log
        # commit_options: '--no-verify'